### PR TITLE
fix: Check for package.json file to get package manager

### LINKED ISSUE #239: Extension is trying to use npm instead of cargo?
Hi there,

When I run `cargo tauri dev` in the Terminal, my app starts correctly, but when I try using `Tauri: Dev` from the Command Palette, I get this output:

```
npm ERR! Missing script: "tauri"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in: /Users/andrew/.npm/_logs/2024-01-22T17_16_56_539Z-debug-0.log
-----------------------
```

Is there a way to tell it to use cargo instead?

### PR DESCRIPTION
**Pull request by soorya-u**
closes #239

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -413,6 +413,14 @@ function __getNpmCommand() {
 }
 
 function __getPackageManagerCommand(projectPath: string): string | null {
+  const isNodeProject = __isNodeProject(projectPath)
+  if (!isNodeProject) return 'cargo'
+
+  const packageJson = JSON.parse(
+    fs.readFileSync(`${projectPath}/package.json`, 'utf8')
+  )
+  if (!packageJson.script || !packageJson.script['tauri']) return 'cargo'
```
Comment (amrbashir) [inline src/extension.ts]: This is not necessarily true, when using pnpm or yarn, you don't need a `tauri` script in package.json

Comment (soorya-u) [reply src/extension.ts]: so this edge case is just for npm?

Comment (soorya-u) [reply src/extension.ts]: I think i have made the necessary changes

**Review by amrbashir — APPROVED** [review]

**Review by amrbashir — APPROVED** [review]
